[project]
name = 'Tokenized-Real-Estate'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fractional-ownership]
path = 'contracts/fractional-ownership.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-management]
path = 'contracts/property-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-tokenization]
path = 'contracts/property-tokenization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
